## Steven Rothaus
### Monday: Problem Set 8

### Most datasets that you will encounter in practice need some degree of wrangling before they're ready to be analyzed. For today, you'll experiment using ETL to clean up a dataset scraped from MySpace, a social media platform. Write a Python script called dataWrangling.py to clean the data in dd-comment-profile.csv file. Your Python file should contain a function called generateCleanFile that takes as input (1) the name of the file to be cleaned and (2) the name of the file to be generated that will hold the cleaned data. Your code should clean the data in the following ways:

In [36]:
#Should contain a function called generateCleanFile that takes as input 
#(1) the name of the file to be cleaned
#(2) the name of the file to be generated that will hold the cleaned data.
#Only use for .py
#def generateCleanFile(input_file, output_file):
    #df = pd.read_csv(input_file, encoding="latin1")
    
#df.to_csv(output_file)
#file.close()
#generateCleanFile("dd-comment-profile.csv", "dd-comment-profile-revised-clean.csv")

In [25]:
import pandas as pd
#Import File, check read
#Use simple read for python test.
#Only use for .ipynb
df = pd.read_csv("dd-comment-profile.csv", encoding='latin1')
#df.head(10)

/Users/Steven/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,comment_id,comment_date,comment_postmortem_ind,comment_msg,deceased_id,profile_account_id
0,1,40271.112500,1.0,colby miss you and love you. tell richard we m...,3.0,3.0
1,2,40257.681250,1.0,<div>There is not a day that goes by that i do...,3.0,3.0
2,3,40233.061806,1.0,colby we miss u soo much we wish u didnt have ...,3.0,3.0
3,4,40230.115278,1.0,looove you uncle&lt;33333\r\r\rforever and always,3.0,3.0
4,5,40219.101389,1.0,missss youuuu aloooooooooot &lt;3333,3.0,3.0
5,6,40211.040972,1.0,<div>Love you and miss you !!!!æ I wish u wer...,3.0,3.0
6,7,40208.127083,1.0,"<font size=""5"">i love you (heart)</font>",3.0,3.0
7,8,40202.810417,1.0,everythingæwould be so much better if you wer...,3.0,3.0
8,9,40196.945833,1.0,hey colby its izzy i miss you bud you touched ...,3.0,3.0
9,10,40194.934028,1.0,colby I love and miss you so much!!!!!<img src...,3.0,3.0

In [37]:
#Correct length to work for code/check back with finished
len(df)

440576

In [38]:
#Stock text,(compare/rerun to 2 output)
df["comment_msg"]
df.head(10)

,comment_id,comment_date,comment_postmortem_ind,comment_msg,deceased_id,profile_account_id
0,1,40271.112500,1.0,colby miss you and love you. tell richard we m...,3.0,3.0
1,2,40257.681250,1.0,there is not a day that goes by that i don't t...,3.0,3.0
2,3,40233.061806,1.0,colby we miss u soo much we wish u didnt have ...,3.0,3.0
3,4,40230.115278,1.0,looove you uncle&lt;33333forever and always,3.0,3.0
4,5,40219.101389,1.0,missss youuuu aloooooooooot &lt;3333,3.0,3.0
5,6,40211.040972,1.0,love you and miss you !!!!æ i wish u were her...,3.0,3.0
6,7,40208.127083,1.0,i love you (heart),3.0,3.0
7,8,40202.810417,1.0,everythingæwould be so much better if you wer...,3.0,3.0
8,9,40196.945833,1.0,hey colby its izzy i miss you bud you touched ...,3.0,3.0
9,10,40194.934028,1.0,colby i love and miss you so much!!!!!,3.0,3.0

### 2. Remove HTML Tags: Since this data has been scraped from the web, it contains a number of HTML tags that indicate components of the DOM but aren't useful for analysis. Remove any HTML tags, but keep the contents of the comment. For example, "< div > Hi, Mike! < /div >" will become Hi, Mike!
### (Aaron advised we solved by starting with 2)

In [39]:
#Number 2
#Import re function(https://docs.python.org/3/library/re.html)
import re
#Remove as many special and standard HTML style characters(https://lzone.de/examples/Python%20re.sub)
def HTMLRevision(df):
    #df['comment_msg'] = df['comment_msg'].apply(lambda x: str(x).lstrip())
    df['comment_msg'] = df['comment_msg'].apply(lambda x: str(x).strip())
    df['comment_msg'] = df['comment_msg'].apply(lambda x: re.sub(r'\r*',"", str(x)))
    df['comment_msg'] = df['comment_msg'].apply(lambda x: re.sub(r'<.*?>',"",str(x)))
#Return and check re edit changes
    return df    
clean_html_df = HTMLRevision(df)
clean_html_df.head(10)

,comment_id,comment_date,comment_postmortem_ind,comment_msg,deceased_id,profile_account_id
0,1,40271.112500,1.0,colby miss you and love you. tell richard we m...,3.0,3.0
1,2,40257.681250,1.0,there is not a day that goes by that i don't t...,3.0,3.0
2,3,40233.061806,1.0,colby we miss u soo much we wish u didnt have ...,3.0,3.0
3,4,40230.115278,1.0,looove you uncle&lt;33333forever and always,3.0,3.0
4,5,40219.101389,1.0,missss youuuu aloooooooooot &lt;3333,3.0,3.0
5,6,40211.040972,1.0,love you and miss you !!!!æ i wish u were her...,3.0,3.0
6,7,40208.127083,1.0,i love you (heart),3.0,3.0
7,8,40202.810417,1.0,everythingæwould be so much better if you wer...,3.0,3.0
8,9,40196.945833,1.0,hey colby its izzy i miss you bud you touched ...,3.0,3.0
9,10,40194.934028,1.0,colby i love and miss you so much!!!!!,3.0,3.0

In [40]:
#Should only clean, not remove data. Check length.
len(clean_html_df)

440576

### 1. Remove spam: Some comments on social media contain spam and aren't useful for our analysis. We can determine comments that are spam by removing any comments containing a web address or any of the following keywords: App, FREE, %20, Check out my page. Note that these keywords are NOT case sensitive (e.g., you should remove comments containing APP, app, App, APp, etc.).

In [41]:
#Number 1
#Remove web address content(http.www.com)/App, FREE, %20, Check out my page.(Not case sensitive, remove all variations)
def SpamRevision(clean_html_df):
    clean_html_df['comment_msg'] = clean_html_df['comment_msg'].apply(lambda x: x.lower())
    spam_comments_remove = ['app', 'free', '%20', 'check out my page', 'http://', 'www.', '.com']
    clean_html_df = clean_html_df[clean_html_df.comment_msg.str.contains('|'.join(spam_comments_remove)) == False]
#Return and check re edit changes    
    return clean_html_df
clean_html_spam_df = SpamRevision(df)
clean_html_spam_df.head(10)

,comment_id,comment_date,comment_postmortem_ind,comment_msg,deceased_id,profile_account_id
0,1,40271.112500,1.0,colby miss you and love you. tell richard we m...,3.0,3.0
1,2,40257.681250,1.0,there is not a day that goes by that i don't t...,3.0,3.0
2,3,40233.061806,1.0,colby we miss u soo much we wish u didnt have ...,3.0,3.0
3,4,40230.115278,1.0,looove you uncle&lt;33333forever and always,3.0,3.0
4,5,40219.101389,1.0,missss youuuu aloooooooooot &lt;3333,3.0,3.0
5,6,40211.040972,1.0,love you and miss you !!!!æ i wish u were her...,3.0,3.0
6,7,40208.127083,1.0,i love you (heart),3.0,3.0
7,8,40202.810417,1.0,everythingæwould be so much better if you wer...,3.0,3.0
8,9,40196.945833,1.0,hey colby its izzy i miss you bud you touched ...,3.0,3.0
9,10,40194.934028,1.0,colby i love and miss you so much!!!!!,3.0,3.0

In [42]:
len(clean_html_spam_df)

332197

### 3. Remove Missing Data: The data collection script used to scrape MySpace inserted null values in cases where the data collection was unable to process meaningful content. Remove all rows where the message is null.

In [43]:
#Number 3
#Remove null values given to unprocessable content.(null/nan)
def NullRevision(clean_html_spam_df):
    clean_html_spam_df = clean_html_spam_df[df['comment_msg'] != "nan"]
    clean_html_spam_df = clean_html_spam_df[df['comment_msg'] != "null"]
    clean_html_spam_df = clean_html_spam_df[df['comment_msg'] != ""]
    df.dropna()
#Return and check null/nan edit changes    
    return clean_html_spam_df
final_clean_df = NullRevision(clean_html_spam_df)
final_clean_df.head(10)

/Users/Steven/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.
/Users/Steven/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:5: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """
/Users/Steven/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,comment_id,comment_date,comment_postmortem_ind,comment_msg,deceased_id,profile_account_id
0,1,40271.112500,1.0,colby miss you and love you. tell richard we m...,3.0,3.0
1,2,40257.681250,1.0,there is not a day that goes by that i don't t...,3.0,3.0
2,3,40233.061806,1.0,colby we miss u soo much we wish u didnt have ...,3.0,3.0
3,4,40230.115278,1.0,looove you uncle&lt;33333forever and always,3.0,3.0
4,5,40219.101389,1.0,missss youuuu aloooooooooot &lt;3333,3.0,3.0
5,6,40211.040972,1.0,love you and miss you !!!!æ i wish u were her...,3.0,3.0
6,7,40208.127083,1.0,i love you (heart),3.0,3.0
7,8,40202.810417,1.0,everythingæwould be so much better if you wer...,3.0,3.0
8,9,40196.945833,1.0,hey colby its izzy i miss you bud you touched ...,3.0,3.0
9,10,40194.934028,1.0,colby i love and miss you so much!!!!!,3.0,3.0

In [44]:
len(final_clean_df)

312026